# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Vendor Bill",
    "version": "14.0.2.2.3",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "contributors": [
        "Andhitia Rama <andhitia.r@gmail.com>",
    ],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "depends": [
        "ssi_financial_accounting",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_date_due_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_company_currency_mixin",
        "ssi_m2o_configurator_mixin",
        "ssi_product_line_account_mixin",
        "ssi_accounting_entry_mixin",
        "ssi_transaction_pricelist_mixin",
        "base_automation",
        "web_tour",
    ],
    "data": [
        "security/ir_module_category/vendor_bill.xml",
        "security/res_groups/vendor_bill.xml",
        "security/res_groups/vendor_bill_type.xml",
        "security/ir_model_access/vendor_bill.xml",
        "security/ir_model_access/vendor_bill_type.xml",
        "security/ir_rule/vendor_bill.xml",
        "ir_sequence/vendor_bill.xml",
        "sequence_template/vendor_bill.xml",
        "approval_template/vendor_bill.xml",
        "policy_template/vendor_bill.xml",
        "data/ir_actions_server.xml",
        "data/base_automation.xml",
        "views/vendor_bill.xml",
        "views/vendor_bill_type_views.xml",
        "views/assets.xml",
    ],
    "demo": [],
}
